apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dvatl90b1-python
  janus-idp.io/tekton: dvatl90b1-python
  backstage.io/kubernetes-id: dvatl90b1-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dvatl90b1-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
